### ISSUE TITLE
comprendre comment marche l’auth dans le REST de basex

### ISSUE THREAD

**Issue by lakonis** [timoguic/sp_hub#10]

**Comment by lakonis** [comment]
Voir la doc : http://docs.basex.org/wiki/Web_Application

**Comment by timoguic** [comment]
J'ai lu la doc, et je n'ai pas compris ce point: "By default, RESTXQ uses the admin user, whereas the REST and WebDAV services require client-side authentication. A default user can be specified via command-line arguments. In the web.xml file, both a global and a servlet-specific user can be added (see above)."

BaseX est une boîte noire pour moi. C'est toi qui a fait marcher les requêtes RESTXQ... Est-ce que tu pourrais les transformer en service REST, que ce soit cohérent avec le reste de l'application?

**Comment by lakonis** [comment]
:sweat:

**Comment by timoguic** [comment]
Pas de BaseX pour le moment.
