### ISSUE TITLE
Définir le modèle de données (choix SQL/NoSQL)

### ISSUE THREAD

**Issue by lakonis** [timoguic/sp_hub#11]
Le projet éditorial tend à croiser deux réseaux (2 graphes) : 
1. un réseau de documents, avec :
  * des liens forts directes (une bibliographie) ou indirecte (via des références données en annotation,
  * ou avec des liens faibles inférés par les mots-clés (typiquement une relation entre deux documents taggés par le même mot-clé).
2. un réseau de personnes :
  * des auteurs d'articles
  * des auteurs cités
  * des auteurs "invoqués" par des utilisateurs (une référence dans une annotation par exemple)
  * des lecteurs-contributeurs (annotation et conversation)

Du coup, une organisation des données en graphe pourrait être intéressante.
Par contre, le volume de données que l'on aura justifie-t-il vraiment un nosql, intuitivement pertinent pour des très grandes bases ?

**Comment by timoguic** [comment]
Ca dépend surtout du modèle de données. Pour les mots clés ça a l'air peu structuré (j'ai vu aussi des traductions!) donc ça pourrait être une idée. Quelle est le volume estimé?

**Comment by lakonis** [comment]
Le volume des mots-clés ? des articles ? des contributeurs ?

De ma compréhension limitée, Nosql présentait de l'intérêt pour des (très) grosses bases sujettes à être scindée. Est ce qu'il y aurait d'autres avantages, notamment pour nous ici ?

**Comment by timoguic** [comment]
Le choix est très dépendant de la structure de la taxonomie, qu'il faut préciser. Cf https://github.com/timoguic/sp_hub/blob/master/doc/nosql.json

**Comment by lakonis** [comment]
Le [yaml](https://github.com/EcrituresNumeriques/chaineEditorialeSP/blob/master/yamlSP.md) nous donne un assez bon aperçu des données qui doivent accompagner un article (modulo la gestion plus fine des keywords). 
La gestion des dossiers change dans SP_hub : on devrait pouvoir afficher avec l'article la liste des _Conversations_ auxquelles l'article est associé. 

Il faut aussi prendre en compte la bibliographie d'un article

**Comment by timoguic** [comment]
> Le yaml nous donne un assez bon aperçu des données qui doivent accompagner un article (modulo la gestion plus fine des keywords).

Malheureusement, les keywords sont le coeur de la plateforme, donc il faut les définir aussi.

Sinon, d'après le YAML, une traduction = un document différent (puisque URL différente), et donc pas une version différente du même document?

**Comment by lakonis** [comment]
j'ai précisé un peu le modèle (nosql.json), notamment pour les objets article et tag. 
Plusieurs questions et précisions en commentaire. C'est une proposition, on en discute quand tu veux.

**Comment by timoguic** [comment]
Tu pourrais reprendre la syntaxe? C'est tout pété et illisible maintenant :(

**Comment by lakonis** [comment]
sérieux ? :) [je croyais](https://github.com/timoguic/sp_hub/issues/14#issuecomment-330849239) que ça me concernait pas la syntaxe ;)

**Comment by timoguic** [comment]
Si tu commences à pousser sur des documents formatés, il faut respecter la syntaxe. Tout comme un éditeur fait attention à ne pas rajouter de fautes quand il corrige un texte. De même l'éditeur définit rarement le format de fichier qui sera utilisé pour échanger entre le maquettiste et l'imprimeur. Non? ;)

**Comment by timoguic** [comment]
Utilisation de PostgreSQL avec JSONField.
