### ISSUE TITLE
Importer les mots clés lors de l'upload d'un fichier dans BaseX et les injecter dans la base de KW éditeur

### ISSUE THREAD

**Issue by timoguic** [timoguic/sp_hub#13]
Après l'upload:
- requêter les KW via l'API BaseX
- les ajouter à la base sp_hub si non existant
- mettre en place un mécanisme de récupération lors de l'affichage de l'article

**Comment by lakonis** [comment]
L'affichage de l'article pourrait mobiliser soit l'api basex, soit la base sp_hub (qui devrait être plus complète dans le cas où un mécanisme d'enrichissement des html n'est pas encore mis en place).
Sans doute que tu préfereras mobiliser la base sp_hub.
Mais du coup est ce que la question ne va pas se poser pour toutes les données ?

**Comment by lakonis** [comment]
Pour la requête KW via baseX, j'aurais besoin qu'on se mette d'accord sur un format des données en json. Comme discuté, les keywords dans le html sont pour le moment très pauvres (balise `<meta>`), et on n'en tirera rien d'autre que la chaine de caractère. Mais on doit anticiper le moment où les keywords seront correctement caractérisés par les attributs : 
* lang (fr, en, ..)
* label (string)
* autorité (rameau.bnf.fr)
* uri_autorité (id ark)
* vocabulaire (auteurs, regroupement thématiques, etc.)
* etc.

**Comment by timoguic** [comment]
Je vais faire du xquery sur le HTML moi même, donc il faudrait plutôt les requêtes XQ que le JSON... Qui lui viendra plus tard.

**Comment by timoguic** [comment]
BaseX non nécessaire pour le moment
