### ISSUE TITLE
Nettoyer l'export des KW de SPIP

### ISSUE THREAD

**Issue by timoguic** [timoguic/sp_hub#14]
- A quoi correspond l'id_groupe dans SPIP?
- Quid de la catégorie "regroupements thématiques" vs "thématiques"?
- Certains [mots clés](https://github.com/timoguic/sp_hub/blob/master/doc/spip_mots.csv) sont traduits, d'autres non? Quelle est l'approche ici?

**Comment by lakonis** [comment]
Sur les traductions, il faut qu'on spécifie le format json. 2 approches : 
```
item {
  autorité: "rameau"
  id_autorité: "ark1234567"
  term: {
     lang: "fr"
     label: "philosophie"
  }
  term: {
     lang: "en"
     label: "philosophy"
  }
}
```
ou bien 
```
item {
  lang: "fr"
  label: "philosophie"
  autorité: "rameau"
  id_autorité: "ark1234567"
}
item {
  lang: "en"
  label: "philosophy"
  autorité: "rameau"
  id_autorité: "ark1234567"
}
```

**Comment by lakonis** [comment]
* Regroupement thématique = une liste assez large de sujets abordés (93 entrées environ)
* Thématique = correspond à 6 "disciplines". Un traitement particulier des thématiques a été spécifié [ici](https://github.com/timoguic/sp_hub/blob/master/doc/20170914_RecapReunion9sept.md#th%C3%A9matiques). Les "Thématiques" ne sont pas amenés à disparaitre, mais on aimerait transformer leur fonctionnement: 

  > au lieu de rattacher un article à une Thématique (déclaration via un keyword), on souhaite inférer une thématique à partir du champs sémantique des mots-clés de l'article. Pour cela, je dois préparer les listes des mots-clés des articles de chaque thématique. On aura donc pour chacune un champs sémantique associé.

Il faut discuter de comment on traite cela.

**Comment by lakonis** [comment]
`id_group` == `type` :)

**Comment by ServanneMo** [comment]
Regroupement thématique = titre des dossiers comme ici : http://sens-public.org/article1090.html 
Thématique = topics (ex : Roman, Éditorialisation, Internet)

**Comment by lakonis** [comment]
@ServanneMo n'a pas complètement tort !
mais attention, les Thématiques sont bien les 6 disciplines ou champs d'études.
Les Regroupements Thématiques sont les 93 _topics_ ou _sujets_, mais comprennent aussi les titres de dossiers en effet !
On doit absolument rationaliser cela dans la nouvelle plateforme. Les titres de dossiers n’apparaîtront plus dans les keywords. C'était le hack assez sale que les éditeurs du spip ont trouvé, mais on ne va pas le reproduire.

**Comment by timoguic** [comment]
> On doit absolument rationaliser cela dans la nouvelle plateforme.

D'accord, comment?

**Comment by lakonis** [comment]
Dossier 
: Les dossiers deviennent des Conversations qui contiendront l'article sommaire et les autres articles.

Thématiques
: on en a déjà discuté : soit information déduite du champs sémantique des keywords de l'article, le champs thématique disparait, il est toujours déduit. Soit, on ajoute à l'article un champs "thématique" distincts de keywords.

Regroupements thématiques
: Ce sont nos keywords alignés, potentiellement multi-lingues, représentant les _topics_ ou _sujets_.

**Comment by timoguic** [comment]
Importation SPIP terminée
