### ISSUE TITLE
Alignement Rameau des mot-clés

### ISSUE THREAD

**Issue by lakonis** [timoguic/sp_hub#17]
quels en sont les usages dans spip_hub ?
quelles sont les données pertinentes dans https://github.com/EcrituresNumeriques/spip2erudit/blob/master/groupes.xml ?

**Comment by lakonis** [comment]
1. On ne conserve que les uri.
2. les alignements permettront de récupérer des traductions pour les mots-clés alignés (sur les api disponibles wikidata ou service dédié)

**Comment by timoguic** [comment]
Quel est le problème précisément? A qui s'adressent ces commentaires?

**Comment by lakonis** [comment]
Ce sont des informations supplémentaires pour toi. L'issue est issue de notre discussion.
