### ISSUE TITLE
types d'article

### ISSUE THREAD

**Issue by lakonis** [timoguic/sp_hub#23]
Le "type d'article" est un élément de navigation. Il sera utilisé dans un menu de sélection (comme sur le spip actuel). C'est sans doute une donnée à ajouter pour définir un article. 

* Il y aura 6 types différents : Essai, Chronique, Création, Entretien, Lecture, Sommaire dossier.
* la balise <meta> dans les html à prendre en compte : `<meta name="prism.genre" content="Essai"/>`

**Comment by timoguic** [comment]
Implémenté avec un EnumIntegerField.
