### ISSUE TITLE
Scénario: backend - Ingest/maj article

### ISSUE THREAD

**Issue by lakonis** [timoguic/sp_hub#24]
besoins :
 - créer un nouvel article
 - mettre à jour un article existant
 - batch-créer de nouveaux articles
 - batch-mettre à jour des articles existants

principe : après discussion, on considère que la gestion des fichiers (git) de l'édition des articles reste séparée de la gestion des fichiers côté sphub. Les imports se feront donc via des fichiers locaux.

## Créer un ou plusieurs nouveaux articles
1. l'éditeur prépare un zip, qui contient des dossiers. Dans chaque dossier, il y a un fichier HTML et des dossiers supplémentaires.
2. sur sphub, l'éditeur demande à créer de nouveaux articles
    * l'id de l'article sera créé automatiquement à partir du nom du fichier HTML
3. sélection et upload du zip depuis le disque dur.
4. ingest : création des entrées BDD
5. éventuellement enrichissement (mot-clé).

## Mettre à jour un article existant

1. ouvrir la page de gestion d'un article
2. bouton upload d'un nouveau fichier html OU bouton "mettre à jour"
3. sélection d'un .html depuis le disque dur
4. ingest : mise-à-jour des entrées BDD. Si nouveau mot-clé, on l'ajoute dans la base. Si mot-clé supprimé, on le conserve dans la base.

## Mettre à jour plusieurs articles à la fois
TBD

**Comment by lakonis** [comment]
Ce scénario évolue, notamment dans le workflow et dans la répartition des rôles. Voir scénario #25.

**Comment by timoguic** [comment]
Je préfère fermer cette issue du coup pour garder les choses claires.
