### ISSUE TITLE
Définir le modèle de permissions

### ISSUE THREAD

**Issue by timoguic** [timoguic/sp_hub#3]
Qui a le droit de faire quoi?
- utilisateur anonyme (non authentifié): visualiser tout
- utilisateur authentifié, rôle éditeur: créer document, éditer document
- y'a t'il besoin de séparer les permissions pour créer un article et une conversation?

**Comment by lakonis** [comment]
Voilà comment on voit les rôles : 
* éditeur : a accès à tout, crée et édite des articles et des conversations
* "directeur de conversation" : est invité à gérer une conversation, il peut créer et éditer une conversation.
* contributeur : qu'il soit auteur d'article ou simple lecteur, il ne peut qu'annoter les articles et participer aux conversations via hypothesis. La distinction d'un auteur d'un lecteur sera probablement déduite du fait que le user "A" est aussi auteur de l'article "SPXXXX".
* passant : non authentifié, il pourrait annoter via son propre compte hypothes.is s'il en a possède un. S'il cherche à se connecter, on devrait lui proposer en priorité de se créer un compte SP qui lui donnera un compte hypothes.is.

**Comment by timoguic** [comment]
Voir #27
