### ISSUE TITLE
Mots-clés alignés

### ISSUE THREAD

**Issue by lakonis** [timoguic/sp_hub#9]
le xml des mots-clés alignés sur https://github.com/EcrituresNumeriques/spip2erudit/blob/master/groupes.xml

**Comment by lakonis** [comment]
Et un export de la table des mots-clés depuis la base de spip : https://github.com/timoguic/sp_hub/blob/master/doc/spip_mots.csv
à noter le vocabulaire dans la colonne "type".

**Comment by timoguic** [comment]
Pas de problématique dans cette issue? Je ferme.
